#!/bin/bash

if [ $# -lt 1 ]; then
    >&2 echo "usage: $(basename "$0") <prog> [ <args> ]"
    exit 1
fi

echo "Hello from $0!"
echo "Args: $*"

# Set environment variable $HOME.
# This is required by DAS and other libraries.
export HOME=/afs/cern.ch/user/l/legao

# Turn to user-specified program.
PROG="$(readlink -f "$1")"
shift 1
eval "${PROG}" "$@"
